services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
        - "8888:8080"
    environment:
        AUTH_SERVICE_URL: http://auth:8080
        SOURCEOFVOICE_SERVICE_URL: http://sourceofvoice:8080
    depends_on:
        - auth
        - redis
    networks:
        - sourceofvoice

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - sourceofvoice
      - auth-postgres-n

  sourceofvoice:
    build:
      context: ./sourceofvoice
      dockerfile: Dockerfile
    networks:
      - sourceofvoice
      - sourceofvoice-postgres-n

  auth-postgres:
    image: postgres
    container_name: "auth-postgres-sourceofvoice"
    ports:
      - "5433:5432"
    networks:
      - auth-postgres-n
    volumes:
      - auth_service_postgres:/var/lib/postgresql/data

  sourceofvoice-postgres:
    image: postgres
    container_name: "sourceofvoice-postgres-sourceofvoice"
    ports:
      - "5434:5432"
    networks:
      - sourceofvoice-postgres-n
    volumes:
      - sourceofvoice_service_postgres:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: refresh_token_redis
    ports:
       - "6379:6379"
    networks:
       - sourceofvoice
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]

volumes:
  auth_service_postgres:
  sourceofvoice_service_postgres:
  redis-data:

networks:
  sourceofvoice:
    driver: bridge
  auth-postgres-n:
    driver: bridge
  sourceofvoice-postgres-n:
    driver: bridge